In [20]:
from optimuskg.pipelines.gold.adapter import (
    BiocypherAdapter,
    EdgeMappingConfig,
    NodeMappingConfig,
)
import polars as pl

In [155]:
ncbigene_protein_go_associations = catalog.load("bronze.ncbigene.protein_go_associations")
go_terms = catalog.load("bronze.ontology.go_terms")
protein_names = catalog.load("bronze.gene_names.protein_names")

[05/23/25 03:17:19] INFO     Loading data from bronze.ncbigene.protein_go_associations    ]8;id=798723;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=809211;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.ontology.go_terms (CSVDataset)...   ]8;id=389062;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=427752;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

                    INFO     Loading data from bronze.gene_names.protein_names            ]8;id=602003;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=201679;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

In [156]:
protein_names

shape: (43_696, 2)
┌────────────────┬──────────┐
│ ncbi_id        ┆ symbol   │
│ ---            ┆ ---      │
│ str            ┆ str      │
╞════════════════╪══════════╡
│ NCBIGene:1     ┆ A1BG     │
│ NCBIGene:10    ┆ NAT2     │
│ NCBIGene:100   ┆ ADA      │
│ NCBIGene:1000  ┆ CDH2     │
│ NCBIGene:10000 ┆ AKT3     │
│ …              ┆ …        │
│ NCBIGene:9992  ┆ KCNE2    │
│ NCBIGene:9993  ┆ DGCR2    │
│ NCBIGene:9994  ┆ CASP8AP2 │
│ NCBIGene:9995  ┆ ELK2BP   │
│ NCBIGene:9997  ┆ SCO2     │
└────────────────┴──────────┘

In [162]:
ncbigene_protein_go_associations

shape: (356_422, 3)
┌──────────────┬────────────┬────────────────────┐
│ ncbi_gene_id ┆ go_term_id ┆ go_term_type       │
│ ---          ┆ ---        ┆ ---                │
│ str          ┆ str        ┆ str                │
╞══════════════╪════════════╪════════════════════╡
│ 1            ┆ GO_0002764 ┆ biological_process │
│ 1            ┆ GO_0005576 ┆ cellular_component │
│ 1            ┆ GO_0005615 ┆ cellular_component │
│ 1            ┆ GO_0005886 ┆ cellular_component │
│ 1            ┆ GO_0031093 ┆ cellular_component │
│ …            ┆ …          ┆ …                  │
│ 131768270    ┆ GO_1901857 ┆ biological_process │
│ 133834869    ┆ GO_0005515 ┆ molecular_function │
│ 133834869    ┆ GO_0005739 ┆ cellular_component │
│ 133834869    ┆ GO_0090324 ┆ biological_process │
│ 133834869    ┆ GO_0160193 ┆ molecular_function │
└──────────────┴────────────┴────────────────────┘

In [163]:
go_terms

shape: (51_676, 3)
┌────────────┬─────────────────────────────────┬───────┐
│ id         ┆ name                            ┆ type  │
│ ---        ┆ ---                             ┆ ---   │
│ str        ┆ str                             ┆ str   │
╞════════════╪═════════════════════════════════╪═══════╡
│ GO_0004075 ┆ biotin carboxylase activity     ┆ CLASS │
│ GO_0046320 ┆ regulation of fatty acid oxida… ┆ CLASS │
│ GO_1990880 ┆ cellular detoxification of cop… ┆ CLASS │
│ GO_1990322 ┆ collagen type XXIII trimer      ┆ CLASS │
│ GO_1903548 ┆ obsolete negative regulation o… ┆ CLASS │
│ …          ┆ …                               ┆ …     │
│ GO_0060294 ┆ cilium movement involved in ce… ┆ CLASS │
│ GO_0044040 ┆ obsolete multi-organism carboh… ┆ CLASS │
│ GO_0045355 ┆ null                            ┆ CLASS │
│ GO_0021567 ┆ rhombomere 1 development        ┆ CLASS │
│ GO_0034066 ┆ Ric1-Rgp1 guanyl-nucleotide ex… ┆ CLASS │
└────────────┴─────────────────────────────────┴───────┘

In [164]:
df_prot_path = ncbigene_protein_go_associations.join(
    go_terms, left_on="go_term_id", right_on="id", how="inner"
)
df_prot_path

shape: (356_422, 5)
┌──────────────┬────────────┬────────────────────┬─────────────────────────────────┬───────┐
│ ncbi_gene_id ┆ go_term_id ┆ go_term_type       ┆ name                            ┆ type  │
│ ---          ┆ ---        ┆ ---                ┆ ---                             ┆ ---   │
│ str          ┆ str        ┆ str                ┆ str                             ┆ str   │
╞══════════════╪════════════╪════════════════════╪═════════════════════════════════╪═══════╡
│ 1            ┆ GO_0002764 ┆ biological_process ┆ immune response-regulating sig… ┆ CLASS │
│ 1            ┆ GO_0005576 ┆ cellular_component ┆ extracellular region            ┆ CLASS │
│ 1            ┆ GO_0005615 ┆ cellular_component ┆ extracellular space             ┆ CLASS │
│ 1            ┆ GO_0005886 ┆ cellular_component ┆ plasma membrane                 ┆ CLASS │
│ 1            ┆ GO_0031093 ┆ cellular_component ┆ platelet alpha granule lumen    ┆ CLASS │
│ …            ┆ …          ┆ …                  ┆ …                               ┆ …     │
│ 131768270    ┆ GO_1901857 ┆ biological_process ┆ positive regulation of cellula… ┆ CLASS │
│ 133834869    ┆ GO_0005515 ┆ molecular_function ┆ protein binding                 ┆ CLASS │
│ 133834869    ┆ GO_0005739 ┆ cellular_component ┆ mitochondrion                   ┆ CLASS │
│ 133834869    ┆ GO_0090324 ┆ biological_process ┆ negative regulation of oxidati… ┆ CLASS │
│ 133834869    ┆ GO_0160193 ┆ molecular_function ┆ L-lactate dehydrogenase inhibi… ┆ CLASS │
└──────────────┴────────────┴────────────────────┴─────────────────────────────────┴───────┘

In [165]:
df_prot_path = df_prot_path.join(
    protein_names, left_on="ncbi_gene_id", right_on="ncbi_id", how="left"
)
df_prot_path

shape: (356_422, 6)
┌──────────────┬────────────┬────────────────────┬────────────────────────────────┬───────┬────────┐
│ ncbi_gene_id ┆ go_term_id ┆ go_term_type       ┆ name                           ┆ type  ┆ symbol │
│ ---          ┆ ---        ┆ ---                ┆ ---                            ┆ ---   ┆ ---    │
│ str          ┆ str        ┆ str                ┆ str                            ┆ str   ┆ str    │
╞══════════════╪════════════╪════════════════════╪════════════════════════════════╪═══════╪════════╡
│ 1            ┆ GO_0002764 ┆ biological_process ┆ immune response-regulating     ┆ CLASS ┆ null   │
│              ┆            ┆                    ┆ sig…                           ┆       ┆        │
│ 1            ┆ GO_0005576 ┆ cellular_component ┆ extracellular region           ┆ CLASS ┆ null   │
│ 1            ┆ GO_0005615 ┆ cellular_component ┆ extracellular space            ┆ CLASS ┆ null   │
│ 1            ┆ GO_0005886 ┆ cellular_component ┆ plasma membrane                ┆ CLASS ┆ null   │
│ 1            ┆ GO_0031093 ┆ cellular_component ┆ platelet alpha granule lumen   ┆ CLASS ┆ null   │
│ …            ┆ …          ┆ …                  ┆ …                              ┆ …     ┆ …      │
│ 131768270    ┆ GO_1901857 ┆ biological_process ┆ positive regulation of         ┆ CLASS ┆ null   │
│              ┆            ┆                    ┆ cellula…                       ┆       ┆        │
│ 133834869    ┆ GO_0005515 ┆ molecular_function ┆ protein binding                ┆ CLASS ┆ null   │
│ 133834869    ┆ GO_0005739 ┆ cellular_component ┆ mitochondrion                  ┆ CLASS ┆ null   │
│ 133834869    ┆ GO_0090324 ┆ biological_process ┆ negative regulation of         ┆ CLASS ┆ null   │
│              ┆            ┆                    ┆ oxidati…                       ┆       ┆        │
│ 133834869    ┆ GO_0160193 ┆ molecular_function ┆ L-lactate dehydrogenase        ┆ CLASS ┆ null   │
│              ┆            ┆                    ┆ inhibi…                        ┆       ┆        │
└──────────────┴────────────┴────────────────────┴────────────────────────────────┴───────┴────────┘

In [168]:
catalog.load('silver.ctd.ctd_exposure_protein_interactions')

[05/23/25 03:19:49] INFO     Loading data from                                            ]8;id=393796;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=512815;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ctd.ctd_exposure_protein_interactions (CSVDataset)...

shape: (0, 10)
┌──────────┬──────────────────┬──────┬────────┬───┬──────┬────────┬────────┬──────────┐
│ relation ┆ display_relation ┆ x_id ┆ x_type ┆ … ┆ y_id ┆ y_type ┆ y_name ┆ y_source │
│ ---      ┆ ---              ┆ ---  ┆ ---    ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---      │
│ str      ┆ str              ┆ str  ┆ str    ┆   ┆ str  ┆ str    ┆ str    ┆ str      │
╞══════════╪══════════════════╪══════╪════════╪═══╪══════╪════════╪════════╪══════════╡
└──────────┴──────────────────┴──────┴────────┴───┴──────┴────────┴────────┴──────────┘