In [3]:
from optimuskg.pipelines.gold.adapter import (
    BiocypherAdapter,
    EdgeMappingConfig,
    NodeMappingConfig,
)
import polars as pl

In [14]:
ctd_exposure_events = catalog.load("landing.ctd.ctd_exposure_events")
ctd_exposure_events.head(2)

[05/26/25 12:12:37] INFO     Loading data from landing.ctd.ctd_exposure_events            ]8;id=62386;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=948511;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ exposures ┆ exposures ┆ stressors ┆ stressors ┆ … ┆ enrollmen ┆ enrollmen ┆ studyfact ┆ column_4 │
│ tressorna ┆ tressorid ┆ ourcecate ┆ ourcedeta ┆   ┆ tstartyea ┆ tendyear  ┆ ors       ┆ 4        │
│ me        ┆ ---       ┆ gory      ┆ ils       ┆   ┆ r         ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│ str       ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1,1,1-tri ┆ C024566   ┆ Commercia ┆ null      ┆ … ┆ 2001      ┆ 2001      ┆ null      ┆ null     │
│ chloroeth ┆           ┆ l product ┆           ┆   ┆           ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1,1,1-tri ┆ C024566   ┆ Commercia ┆ null      ┆ … ┆ 2001      ┆ 2001      ┆ null      ┆ null     │
│ chloroeth ┆           ┆ l product ┆           ┆   ┆           ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
bronze_ctd_exposure_events = catalog.load("bronze.ctd.ctd_exposure_events")
bronze_ctd_exposure_events.head(2)

[05/26/25 12:13:16] INFO     Loading data from bronze.ctd.ctd_exposure_events             ]8;id=406934;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=896129;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ exposure_ ┆ exposure_ ┆ stressor_ ┆ stressor_ ┆ … ┆ associate ┆ enrollmen ┆ enrollmen ┆ study_fa │
│ stressor_ ┆ stressor_ ┆ source_ca ┆ source_de ┆   ┆ d_study_t ┆ t_start_y ┆ t_end_yea ┆ ctors    │
│ name      ┆ id        ┆ tegory    ┆ tails     ┆   ┆ itles     ┆ ear       ┆ r         ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1,1,1-tri ┆ C024566   ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆           ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ C024566   ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆           ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
bronze_gene_names_protein_names = catalog.load("bronze.gene_names.protein_names")
bronze_gene_names_protein_names.head(2)

[05/26/25 12:15:13] INFO     Loading data from bronze.gene_names.protein_names            ]8;id=739715;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=910780;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 2)
┌─────────────┬────────┐
│ ncbi_id     ┆ symbol │
│ ---         ┆ ---    │
│ str         ┆ str    │
╞═════════════╪════════╡
│ NCBIGene:1  ┆ A1BG   │
│ NCBIGene:10 ┆ NAT2   │
└─────────────┴────────┘

In [28]:
df_exp_prot = bronze_ctd_exposure_events.select(
    [
        "exposure_stressor_name",
        "exposure_stressor_id",
        "exposure_marker",
        "exposure_marker_id",
    ]
)
df_exp_prot = df_exp_prot.filter(pl.col("exposure_marker_id").is_not_null())
# Filter for numeric values in exposure_marker_id
df_exp_prot = df_exp_prot.filter(pl.col("exposure_marker_id").str.contains(r"^\d+$"))
df_exp_prot = df_exp_prot.with_columns(
    pl.col("exposure_marker_id").map_elements(
        lambda x: f"NCBIGene:{x}",
        return_dtype=pl.Utf8,
    )  # Add "NCBIGene:" prefix to ncbi_id column to match biolink schema
)
df_exp_prot

shape: (5_882, 4)
┌────────────────────────┬──────────────────────┬─────────────────┬────────────────────┐
│ exposure_stressor_name ┆ exposure_stressor_id ┆ exposure_marker ┆ exposure_marker_id │
│ ---                    ┆ ---                  ┆ ---             ┆ ---                │
│ str                    ┆ str                  ┆ str             ┆ str                │
╞════════════════════════╪══════════════════════╪═════════════════╪════════════════════╡
│ 1-hydroxyphenanthrene  ┆ C092102              ┆ CRP             ┆ NCBIGene:1401      │
│ 1-hydroxypyrene        ┆ C033146              ┆ ALCAM           ┆ NCBIGene:214       │
│ 1-hydroxypyrene        ┆ C033146              ┆ BDNF            ┆ NCBIGene:627       │
│ 1-hydroxypyrene        ┆ C033146              ┆ CRP             ┆ NCBIGene:1401      │
│ 1-hydroxypyrene        ┆ C033146              ┆ SAA1            ┆ NCBIGene:6288      │
│ …                      ┆ …                    ┆ …               ┆ …                  │
│ Zirconium              ┆ D015040              ┆ MIR193A         ┆ NCBIGene:406968    │
│ Zirconium              ┆ D015040              ┆ MIR323A         ┆ NCBIGene:442897    │
│ Zirconium              ┆ D015040              ┆ MIR335          ┆ NCBIGene:442904    │
│ Zirconium              ┆ D015040              ┆ MIR494          ┆ NCBIGene:574452    │
│ Zirconium              ┆ D015040              ┆ MIR99B          ┆ NCBIGene:407056    │
└────────────────────────┴──────────────────────┴─────────────────┴────────────────────┘

In [29]:
df_exp_prot = df_exp_prot.join(
    bronze_gene_names_protein_names,
    left_on="exposure_marker_id",
    right_on="ncbi_id",
    how="left",
)
df_exp_prot

shape: (5_882, 5)
┌────────────────────────┬──────────────────────┬─────────────────┬────────────────────┬─────────┐
│ exposure_stressor_name ┆ exposure_stressor_id ┆ exposure_marker ┆ exposure_marker_id ┆ symbol  │
│ ---                    ┆ ---                  ┆ ---             ┆ ---                ┆ ---     │
│ str                    ┆ str                  ┆ str             ┆ str                ┆ str     │
╞════════════════════════╪══════════════════════╪═════════════════╪════════════════════╪═════════╡
│ 1-hydroxyphenanthrene  ┆ C092102              ┆ CRP             ┆ NCBIGene:1401      ┆ CRP     │
│ 1-hydroxypyrene        ┆ C033146              ┆ ALCAM           ┆ NCBIGene:214       ┆ ALCAM   │
│ 1-hydroxypyrene        ┆ C033146              ┆ BDNF            ┆ NCBIGene:627       ┆ BDNF    │
│ 1-hydroxypyrene        ┆ C033146              ┆ CRP             ┆ NCBIGene:1401      ┆ CRP     │
│ 1-hydroxypyrene        ┆ C033146              ┆ SAA1            ┆ NCBIGene:6288      ┆ SAA1    │
│ …                      ┆ …                    ┆ …               ┆ …                  ┆ …       │
│ Zirconium              ┆ D015040              ┆ MIR193A         ┆ NCBIGene:406968    ┆ MIR193A │
│ Zirconium              ┆ D015040              ┆ MIR323A         ┆ NCBIGene:442897    ┆ MIR323A │
│ Zirconium              ┆ D015040              ┆ MIR335          ┆ NCBIGene:442904    ┆ MIR335  │
│ Zirconium              ┆ D015040              ┆ MIR494          ┆ NCBIGene:574452    ┆ MIR494  │
│ Zirconium              ┆ D015040              ┆ MIR99B          ┆ NCBIGene:407056    ┆ MIR99B  │
└────────────────────────┴──────────────────────┴─────────────────┴────────────────────┴─────────┘

In [30]:
df_exp_prot = df_exp_prot.rename(
    {
        "exposure_stressor_id": "x_id",
        "exposure_stressor_name": "x_name",
        "exposure_marker_id": "y_id",
        "symbol": "y_name",
    }
)

# Add relationship information
df_exp_prot = df_exp_prot.with_columns(
    [
        pl.lit("exposure").alias("x_type"),
        pl.lit("CTD").alias("x_source"),
        pl.lit("gene").alias("y_type"),
        pl.lit("NCBI").alias("y_source"),
        pl.lit("exposure_protein").alias("relation"),
        pl.lit("interacts with").alias("display_relation"),
    ]
)
df_exp_prot

shape: (5_882, 11)
┌────────────┬─────────┬────────────┬────────────┬───┬────────┬──────────┬────────────┬────────────┐
│ x_name     ┆ x_id    ┆ exposure_m ┆ y_id       ┆ … ┆ y_type ┆ y_source ┆ relation   ┆ display_re │
│ ---        ┆ ---     ┆ arker      ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---        ┆ lation     │
│ str        ┆ str     ┆ ---        ┆ str        ┆   ┆ str    ┆ str      ┆ str        ┆ ---        │
│            ┆         ┆ str        ┆            ┆   ┆        ┆          ┆            ┆ str        │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════╪══════════╪════════════╪════════════╡
│ 1-hydroxyp ┆ C092102 ┆ CRP        ┆ NCBIGene:1 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│ henanthren ┆         ┆            ┆ 401        ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ e          ┆         ┆            ┆            ┆   ┆        ┆          ┆            ┆            │
│ 1-hydroxyp ┆ C033146 ┆ ALCAM      ┆ NCBIGene:2 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│ yrene      ┆         ┆            ┆ 14         ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ 1-hydroxyp ┆ C033146 ┆ BDNF       ┆ NCBIGene:6 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│ yrene      ┆         ┆            ┆ 27         ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ 1-hydroxyp ┆ C033146 ┆ CRP        ┆ NCBIGene:1 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│ yrene      ┆         ┆            ┆ 401        ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ 1-hydroxyp ┆ C033146 ┆ SAA1       ┆ NCBIGene:6 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│ yrene      ┆         ┆            ┆ 288        ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ …          ┆ …       ┆ …          ┆ …          ┆ … ┆ …      ┆ …        ┆ …          ┆ …          │
│ Zirconium  ┆ D015040 ┆ MIR193A    ┆ NCBIGene:4 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│            ┆         ┆            ┆ 06968      ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ Zirconium  ┆ D015040 ┆ MIR323A    ┆ NCBIGene:4 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│            ┆         ┆            ┆ 42897      ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ Zirconium  ┆ D015040 ┆ MIR335     ┆ NCBIGene:4 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│            ┆         ┆            ┆ 42904      ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ Zirconium  ┆ D015040 ┆ MIR494     ┆ NCBIGene:5 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│            ┆         ┆            ┆ 74452      ┆   ┆        ┆          ┆ rotein     ┆ with       │
│ Zirconium  ┆ D015040 ┆ MIR99B     ┆ NCBIGene:4 ┆ … ┆ gene   ┆ NCBI     ┆ exposure_p ┆ interacts  │
│            ┆         ┆            ┆ 07056      ┆   ┆        ┆          ┆ rotein     ┆ with       │
└────────────┴─────────┴────────────┴────────────┴───┴────────┴──────────┴────────────┴────────────┘