In [1]:
from optimuskg.pipelines.gold.adapter import (
    BiocypherAdapter,
    EdgeMappingConfig,
    NodeMappingConfig,
)
import polars as pl

In [2]:
ctd_exposure_events = catalog.load("landing.ctd.ctd_exposure_events")
ctd_exposure_events.head(2)

[05/26/25 17:57:02] INFO     Loading data from landing.ctd.ctd_exposure_events            ]8;id=261661;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=592523;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ exposures ┆ exposures ┆ stressors ┆ stressors ┆ … ┆ enrollmen ┆ enrollmen ┆ studyfact ┆ column_4 │
│ tressorna ┆ tressorid ┆ ourcecate ┆ ourcedeta ┆   ┆ tstartyea ┆ tendyear  ┆ ors       ┆ 4        │
│ me        ┆ ---       ┆ gory      ┆ ils       ┆   ┆ r         ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│ str       ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1,1,1-tri ┆ C024566   ┆ Commercia ┆ null      ┆ … ┆ 2001      ┆ 2001      ┆ null      ┆ null     │
│ chloroeth ┆           ┆ l product ┆           ┆   ┆           ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1,1,1-tri ┆ C024566   ┆ Commercia ┆ null      ┆ … ┆ 2001      ┆ 2001      ┆ null      ┆ null     │
│ chloroeth ┆           ┆ l product ┆           ┆   ┆           ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
bronze_ctd_exposure_events = catalog.load("bronze.ctd.ctd_exposure_events")
bronze_ctd_exposure_events.head(2)

[05/26/25 17:57:08] INFO     Loading data from bronze.ctd.ctd_exposure_events             ]8;id=198534;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=489451;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ exposure_ ┆ exposure_ ┆ stressor_ ┆ stressor_ ┆ … ┆ associate ┆ enrollmen ┆ enrollmen ┆ study_fa │
│ stressor_ ┆ stressor_ ┆ source_ca ┆ source_de ┆   ┆ d_study_t ┆ t_start_y ┆ t_end_yea ┆ ctors    │
│ name      ┆ id        ┆ tegory    ┆ tails     ┆   ┆ itles     ┆ ear       ┆ r         ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
bronze_gene_names_protein_names = catalog.load("bronze.gene_names.protein_names")
bronze_gene_names_protein_names.head(2)

[05/26/25 18:18:36] INFO     Loading data from bronze.gene_names.protein_names            ]8;id=918284;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=885007;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 2)
┌─────────────┬────────┐
│ ncbi_id     ┆ symbol │
│ ---         ┆ ---    │
│ str         ┆ str    │
╞═════════════╪════════╡
│ NCBIGene:1  ┆ A1BG   │
│ NCBIGene:10 ┆ NAT2   │
└─────────────┴────────┘

In [17]:
ctd_exposure_events = catalog.load("bronze.ctd.ctd_exposure_events")
ctd_exposure_events.head(2)

[05/26/25 18:21:37] INFO     Loading data from bronze.ctd.ctd_exposure_events             ]8;id=813843;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=772831;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (2, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ exposure_ ┆ exposure_ ┆ stressor_ ┆ stressor_ ┆ … ┆ associate ┆ enrollmen ┆ enrollmen ┆ study_fa │
│ stressor_ ┆ stressor_ ┆ source_ca ┆ source_de ┆   ┆ d_study_t ┆ t_start_y ┆ t_end_yea ┆ ctors    │
│ name      ┆ id        ┆ tegory    ┆ tails     ┆   ┆ itles     ┆ ear       ┆ r         ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
unique_exposures = ctd_exposure_events.select("exposure_stressor_id").unique()
df_exp_exp = ctd_exposure_events.filter(
    pl.col("exposure_marker_id").is_in(
        unique_exposures.get_column("exposure_stressor_id")
    )
)
df_exp_exp = df_exp_exp.select(
    [
        "exposure_stressor_name",
        "exposure_stressor_id",
        "exposure_marker",
        "exposure_marker_id",
    ]
).filter(pl.col("exposure_marker_id").is_not_null())
df_exp_exp = df_exp_exp.unique()
df_exp_exp = df_exp_exp.rename(
    {
        "exposure_stressor_id": "x_id",
        "exposure_stressor_name": "x_name",
        "exposure_marker": "y_name",
        "exposure_marker_id": "y_id",
    }
)

# Add relationship information
df_exp_exp = df_exp_exp.with_columns(
    [
        pl.lit("exposure").alias("x_type"),
        pl.lit("CTD").alias("x_source"),
        pl.lit("exposure").alias("y_type"),
        pl.lit("CTD").alias("y_source"),
        pl.lit("exposure_exposure").alias("relation"),
        pl.lit("parent-child").alias("display_relation"),
    ]
)
df_exp_exp

shape: (3_401, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ x_name     ┆ x_id      ┆ y_name    ┆ y_id      ┆ … ┆ y_type   ┆ y_source ┆ relation  ┆ display_r │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---       ┆ elation   │
│ str        ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ str      ┆ str       ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ Parabens   ┆ MESH:D010 ┆ propylpar ┆ MESH:C006 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│            ┆ 226       ┆ aben      ┆ 068       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ Petroleum  ┆ MESH:D010 ┆ Acetone   ┆ MESH:D000 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│            ┆ 578       ┆           ┆ 096       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ 2,2',3,3', ┆ MESH:C511 ┆ 2,2',3,3' ┆ MESH:C511 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ 4,4',6,6'- ┆ 855       ┆ ,4,4',6,6 ┆ 855       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ octabromod ┆           ┆ '-octabro ┆           ┆   ┆          ┆          ┆           ┆           │
│ …          ┆           ┆ mod…      ┆           ┆   ┆          ┆          ┆           ┆           │
│ ethyl-p-hy ┆ MESH:C012 ┆ ethyl-p-h ┆ MESH:C012 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ droxybenzo ┆ 313       ┆ ydroxyben ┆ 313       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ ate        ┆           ┆ zoate     ┆           ┆   ┆          ┆          ┆           ┆           │
│ Endocrine  ┆ MESH:D052 ┆ methylpar ┆ MESH:C015 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ Disruptors ┆ 244       ┆ aben      ┆ 358       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ Disinfecta ┆ MESH:D004 ┆ Triclosan ┆ MESH:D014 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ nts        ┆ 202       ┆           ┆ 260       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ Pesticides ┆ MESH:D010 ┆ Aldrin    ┆ MESH:D000 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│            ┆ 575       ┆           ┆ 452       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ perfluoroh ┆ MESH:C471 ┆ Chlorides ┆ MESH:D002 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ exanesulfo ┆ 071       ┆           ┆ 712       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ nic acid   ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 3,3'-dichl ┆ MESH:C029 ┆ 3,3'-dich ┆ MESH:C029 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ orobipheny ┆ 906       ┆ lorobiphe ┆ 906       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│ l          ┆           ┆ nyl       ┆           ┆   ┆          ┆          ┆           ┆           │
│ Trichloroa ┆ MESH:D014 ┆ Trichloro ┆ MESH:D014 ┆ … ┆ exposure ┆ CTD      ┆ exposure_ ┆ parent-ch │
│ cetic Acid ┆ 238       ┆ acetic    ┆ 238       ┆   ┆          ┆          ┆ exposure  ┆ ild       │
│            ┆           ┆ Acid      ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [9]:
df_exp_prot = bronze_ctd_exposure_events.select(
    [
        "exposure_stressor_name",
        "exposure_stressor_id",
        "exposure_marker",
        "exposure_marker_id",
    ]
)
df_exp_prot = df_exp_prot.filter(pl.col("exposure_marker_id").is_not_null())
# Filter for numeric values in exposure_marker_id
df_exp_prot = df_exp_prot.filter(pl.col("exposure_marker_id").str.contains(r"^\d+$"))
df_exp_prot = df_exp_prot.with_columns(
    pl.col("exposure_marker_id").map_elements(
        lambda x: f"NCBIGene:{x}",
        return_dtype=pl.Utf8,
    )  # Add "NCBIGene:" prefix to ncbi_id column to match biolink schema
)
df_exp_prot

shape: (0, 4)
┌────────────────────────┬──────────────────────┬─────────────────┬────────────────────┐
│ exposure_stressor_name ┆ exposure_stressor_id ┆ exposure_marker ┆ exposure_marker_id │
│ ---                    ┆ ---                  ┆ ---             ┆ ---                │
│ str                    ┆ str                  ┆ str             ┆ str                │
╞════════════════════════╪══════════════════════╪═════════════════╪════════════════════╡
└────────────────────────┴──────────────────────┴─────────────────┴────────────────────┘

In [6]:
df_exp_prot = df_exp_prot.join(
    bronze_gene_names_protein_names,
    left_on="exposure_marker_id",
    right_on="ncbi_id",
    how="left",
)
df_exp_prot

shape: (0, 5)
┌────────────────────────┬──────────────────────┬─────────────────┬────────────────────┬────────┐
│ exposure_stressor_name ┆ exposure_stressor_id ┆ exposure_marker ┆ exposure_marker_id ┆ symbol │
│ ---                    ┆ ---                  ┆ ---             ┆ ---                ┆ ---    │
│ str                    ┆ str                  ┆ str             ┆ str                ┆ str    │
╞════════════════════════╪══════════════════════╪═════════════════╪════════════════════╪════════╡
└────────────────────────┴──────────────────────┴─────────────────┴────────────────────┴────────┘

In [7]:
df_exp_prot = df_exp_prot.rename(
    {
        "exposure_stressor_id": "x_id",
        "exposure_stressor_name": "x_name",
        "exposure_marker_id": "y_id",
        "symbol": "y_name",
    }
)

# Add relationship information
df_exp_prot = df_exp_prot.with_columns(
    [
        pl.lit("exposure").alias("x_type"),
        pl.lit("CTD").alias("x_source"),
        pl.lit("gene").alias("y_type"),
        pl.lit("NCBI").alias("y_source"),
        pl.lit("exposure_protein").alias("relation"),
        pl.lit("interacts with").alias("display_relation"),
    ]
)
df_exp_prot

shape: (0, 11)
┌────────┬──────┬─────────────────┬──────┬───┬────────┬──────────┬──────────┬──────────────────┐
│ x_name ┆ x_id ┆ exposure_marker ┆ y_id ┆ … ┆ y_type ┆ y_source ┆ relation ┆ display_relation │
│ ---    ┆ ---  ┆ ---             ┆ ---  ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---              │
│ str    ┆ str  ┆ str             ┆ str  ┆   ┆ str    ┆ str      ┆ str      ┆ str              │
╞════════╪══════╪═════════════════╪══════╪═══╪════════╪══════════╪══════════╪══════════════════╡
└────────┴──────┴─────────────────┴──────┴───┴────────┴──────────┴──────────┴──────────────────┘