In [2]:
import re
from optimuskg.pipelines.gold.nodes.edges.utils import normalize_edge_topology
import polars as pl

In [3]:
edges = catalog.filter(name_regex=re.compile("^gold.edges."))
edges

[
    'gold.edges.anatomy_protein_present',
    'gold.edges.anatomy_protein_absent',
    'gold.edges.exposure_exposure',
    'gold.edges.exposure_protein',
    'gold.edges.indication',
    'gold.edges.disease_protein',
    'gold.edges.strong_clinical_evidence',
    'gold.edges.weak_clinical_evidence',
    'gold.edges.phenotype_protein',
    'gold.edges.drug_protein',
    'gold.edges.drug_drug',
    'gold.edges.disease_protein_positive',
    'gold.edges.disease_protein_negative',
    'gold.edges.biological_process_protein',
    'gold.edges.cellular_component_protein',
    'gold.edges.molecular_function_protein',
    'gold.edges.pathway_pathway',
    'gold.edges.pathway_protein'
]

In [17]:
ds = catalog.load("gold.edges.exposure_exposure")
# Need to collect() to materialize the filtered results
ds.filter(
    ~(
        pl.struct(["x_id", "x_type", "x_source", "x_name"]).eq(
            pl.struct(["y_id", "y_type", "y_source", "y_name"])
        )
    )
)

[06/06/25 02:46:56] INFO     Loading data from gold.edges.exposure_exposure               ]8;id=324423;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=322883;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

shape: (3_325, 11)
┌────────────┬────────────┬───────────┬──────────┬───┬──────────┬───────────┬──────────┬───────────┐
│ relation   ┆ relation_t ┆ x_id      ┆ x_type   ┆ … ┆ y_type   ┆ y_name    ┆ y_source ┆ undirecte │
│ ---        ┆ ype        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---       ┆ ---      ┆ d         │
│ str        ┆ ---        ┆ str       ┆ str      ┆   ┆ str      ┆ str       ┆ str      ┆ ---       │
│            ┆ str        ┆           ┆          ┆   ┆          ┆           ┆          ┆ bool      │
╞════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪═══════════╪══════════╪═══════════╡
│ exposure_e ┆ parent-chi ┆ MESH:D022 ┆ exposure ┆ … ┆ exposure ┆ chlorodib ┆ CTD      ┆ true      │
│ xposure    ┆ ld         ┆ 882       ┆          ┆   ┆          ┆ romometha ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ ne        ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:C067 ┆ exposure ┆ … ┆ exposure ┆ 2,2',3,3' ┆ CTD      ┆ true      │
│ xposure    ┆ ld         ┆ 940       ┆          ┆   ┆          ┆ ,4,6'-hex ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ achlorobi ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ phe…      ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:D011 ┆ exposure ┆ … ┆ exposure ┆ 2,4,5,2', ┆ CTD      ┆ true      │
│ xposure    ┆ ld         ┆ 078       ┆          ┆   ┆          ┆ 4',5'-hex ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ achlorobi ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ phe…      ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:D002 ┆ exposure ┆ … ┆ exposure ┆ monomethy ┆ CTD      ┆ true      │
│ xposure    ┆ ld         ┆ 101       ┆          ┆   ┆          ┆ larsonic  ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ acid      ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:C541 ┆ exposure ┆ … ┆ exposure ┆ 2,3,3',4, ┆ CTD      ┆ true      │
│ xposure    ┆ ld         ┆ 132       ┆          ┆   ┆          ┆ 4',5-hexa ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ chlorobip ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ hen…      ┆          ┆           │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …        ┆ …         ┆ …        ┆ …         │
│ exposure_e ┆ parent-chi ┆ MESH:D000 ┆ exposure ┆ … ┆ exposure ┆ Fatty     ┆ CTD      ┆ false     │
│ xposure    ┆ ld         ┆ 535       ┆          ┆   ┆          ┆ Acids,    ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ Unsaturat ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ ed        ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:D014 ┆ exposure ┆ … ┆ exposure ┆ Nitrates  ┆ CTD      ┆ false     │
│ xposure    ┆ ld         ┆ 874       ┆          ┆   ┆          ┆           ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:D005 ┆ exposure ┆ … ┆ exposure ┆ Polybromi ┆ CTD      ┆ false     │
│ xposure    ┆ ld         ┆ 411       ┆          ┆   ┆          ┆ nated     ┆          ┆           │
│            ┆            ┆           ┆          ┆   ┆          ┆ Biphenyls ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:D055 ┆ exposure ┆ … ┆ exposure ┆ 1,4-dioxa ┆ CTD      ┆ false     │
│ xposure    ┆ ld         ┆ 549       ┆          ┆   ┆          ┆ ne        ┆          ┆           │
│ exposure_e ┆ parent-chi ┆ MESH:D000 ┆ exposure ┆ … ┆ exposure ┆ pyrene    ┆ CTD      ┆ false     │
│ xposure    ┆ ld         ┆ 395       ┆          ┆   ┆          ┆           ┆          ┆           │
└────────────┴────────────┴───────────┴──────────┴───┴──────────┴───────────┴──────────┴───────────┘

In [ ]:
ds = catalog.load("gold.edges.exposure_exposure")
# Count bidirectional edges by finding pairs where source/target are reversed

[06/06/25 02:57:31] INFO     Loading data from gold.edges.exposure_exposure               ]8;id=491355;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=716422;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

Number of bidirectional edges: 0

In [25]:
dss = []
for ds_name in edges:
    ds = catalog.load(ds_name)
    dss.append(ds)

df = pl.concat(dss)
bidirectional_count = (
    ds.join(ds, left_on=["x_id", "y_id"], right_on=["y_id", "x_id"])
    .filter(pl.col("x_id") != pl.col("y_id"))  # Exclude self-loops
    .height
)
print(f"Number of bidirectional edges: {bidirectional_count}")
df = ds.join(ds, left_on=["x_id", "y_id"], right_on=["y_id", "x_id"])
df

[06/06/25 03:00:16] INFO     Loading data from gold.edges.anatomy_protein_present         ]8;id=93517;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=29470;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.anatomy_protein_absent          ]8;id=312067;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=284025;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.exposure_exposure               ]8;id=471559;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=971394;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.exposure_protein                ]8;id=153788;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=256009;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.indication (CSVDataset)...      ]8;id=587483;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=772322;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

                    INFO     Loading data from gold.edges.disease_protein (CSVDataset)... ]8;id=838248;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=393780;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

                    INFO     Loading data from gold.edges.strong_clinical_evidence        ]8;id=935246;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=223501;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.weak_clinical_evidence          ]8;id=584494;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=895728;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.phenotype_protein               ]8;id=970847;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=454432;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.drug_protein (CSVDataset)...    ]8;id=852070;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=960550;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

                    INFO     Loading data from gold.edges.drug_drug (CSVDataset)...       ]8;id=247339;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=496661;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

                    INFO     Loading data from gold.edges.disease_protein_positive        ]8;id=504970;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=358138;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.disease_protein_negative        ]8;id=68063;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=884356;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.biological_process_protein      ]8;id=118946;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=884899;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.cellular_component_protein      ]8;id=579842;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=468795;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from gold.edges.molecular_function_protein      ]8;id=994876;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=950921;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

[06/06/25 03:00:17] INFO     Loading data from gold.edges.pathway_pathway (CSVDataset)... ]8;id=399537;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=143554;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

                    INFO     Loading data from gold.edges.pathway_protein (CSVDataset)... ]8;id=739570;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=549621;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

Number of bidirectional edges: 0

shape: (0, 20)
┌──────────┬─────────────┬──────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ relation ┆ relation_ty ┆ x_id ┆ x_type ┆ … ┆ y_type_righ ┆ y_name_righ ┆ y_source_r ┆ undirected │
│ ---      ┆ pe          ┆ ---  ┆ ---    ┆   ┆ t           ┆ t           ┆ ight       ┆ _right     │
│ str      ┆ ---         ┆ str  ┆ str    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│          ┆ str         ┆      ┆        ┆   ┆ str         ┆ str         ┆ str        ┆ bool       │
╞══════════╪═════════════╪══════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
└──────────┴─────────────┴──────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘